export const REGISTER_SUCESS = 'REGISTER_SUCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const lOGOUT_SUCESS = 'lOGOUT_SUCESS';
export const AUTHENTICATION_SUCESS = 'AUTHENTICATION_SUCESS';
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';
export const CONNECT_FAILED = 'CONNECT_FAILED';
export const CONNECT_SUCESS ='CONNECT_SUCESS';